theme: jekyll-theme-minimal
title: Michael Ongaro's ePortfolio
description: This is my ePortfolio for CS-499 at Southern New Hampshire University. It showcases three programming artifacts that demonstrate my experience and proficiency in Computer Science.
